schema_version = "1.0.0"

id = "simple_collider"
version = "1.0.1"
name = "Simple Collider"
tagline = "Simple Collider is a Blender addon to create physics colliders for games and real-time applications."
maintainer = "Matthias Patscheider <patscheider.matthias@gmail.com>"
type = "add-on"

website = "https://weisl.github.io/collider_overview/"

tags = ["3D View", "Scene", "User Interface"]

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "linux-x64"]

copyright = [
    "2023 Matthias Patscheider",
]

[permissions]
files = "Write/Read .py preset files from/to disk, copying the Auto Convex executable to execute to avoid the need of manual installation and export/import OBJ files from/to disk for the auto convex generation"


[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
]
